### ISSUE TITLE
Working Directory: Windows Permissions

### ISSUE THREAD

**Issue by OvalAdmin** [LUMC/pytest-workflow#113]
Hi,

I have been using your package upon a Windows machine and it sets up a temporary working directory under the users `C:\Users\USERNAME\AppData\Local\Temp` directory. Once ones test has completed however and your package tries to remove the temporary directory one finds that the permissions are incorrect and the directory cannot be removed. 

I was wondering if there was a configuration setting to alter the location of the temporary working directory ? Otherwise if the fault lies with ones system if you knew of a way to escalate your packages permissions such that it could remove the temporary folder ?

**Comment by rhpvorderman** [comment]
I have no experience with windows and this package.
Does it also occur with tests like:
```
- name: simple test
  command: echo test
```
?
I have had this particular problem on linux as well, but in that case it was the program that created files that could not be removed by the user. So that was not really influencable from pytest-workflow's end.

If the above test fails I can have a look at the permission stuff.

**Comment by rhpvorderman** [comment]
> I was wondering if there was a configuration setting to alter the location of the temporary working directory ? Otherwise if the fault lies with ones system if you knew of a way to escalate your packages permissions such that it could remove the temporary folder ?

Yes you could use the `--basetemp` option. It should be explained clearly here https://pytest-workflow.readthedocs.io/en/stable/#temporary-directory-cleanup-and-creation . If you have suggestions for improving the documentation these are welcome of course.

**Comment by rhpvorderman** [comment]
@OvalAdmin Did you manage to check if this is a windows issue? 

I have made a PR #114 as a workaround. Pytest-workflow behaves in an annoying way when it can't remove directories. It prints a stacktrace and exits with a non-zero exit code. After this fix there will be a message printing the paths that could not be removed, as well as exiting normally.

**Comment by OvalAdmin** [comment]
Thanks for the feedback. I think I got excited trying out your package out and never read the rest of the documentation, my apologies for that. 

I have since tried the command line option and am now encountering the same issue with certain ``git`` objects. I can't say for certain but this seems to have been my issue all along. Is there a way to exclude directories from being copied by ```pytest-workflow`` when the tests are run ? (If not a nice means of doing so might be to employ the same mechanism that Pythons' ``setuptools`` uses for manifest files.)

**Comment by rhpvorderman** [comment]
> Is there a way to exclude directories from being copied by pytest-workflow when the tests are run ?

No. Not yet. But two solutions come to mind:

- Have you tried using the --symlink option? It comes with a caveat, namely that if your tests alter files in the directory it should not be used. If all your tests do is create new files it is save to use. This will create symlinks to all files from your project dir. Presumably (I have not tested this) you have permission to delete these symlinks
- If pytest-workflow would have a git-aware option, the `.git` directory would not be copied, as it does not show up in `git ls-files`

**Comment by rhpvorderman** [comment]
@OvalAdmin Pytest-workflow 1.6.0 now has a `--git-aware` flag that will skip the git folder and any files not checked in to git (including ignored files). Does that solve your issue with the git objects?
