### ISSUE TITLE
pytest-workflow crashes when files in git are removed

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [LUMC/pytest-workflow#129]
pytest-workflow crashes when it is run with `--git-aware` when files that are added in git are removed from the filesystem:

```
../../miniconda3/envs/freebayes-snakemake/lib/python3.10/site-packages/pytest_workflow/plugin.py:439: in collect
    workflow = self.queue_workflow()
../../miniconda3/envs/freebayes-snakemake/lib/python3.10/site-packages/pytest_workflow/plugin.py:397: in queue_workflow
    duplicate_tree(root_dir, tempdir,
../../miniconda3/envs/freebayes-snakemake/lib/python3.10/site-packages/pytest_workflow/util.py:161: in duplicate_tree
    copy(src_path, dest_path)
../../miniconda3/envs/freebayes-snakemake/lib/python3.10/shutil.py:434: in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
../../miniconda3/envs/freebayes-snakemake/lib/python3.10/shutil.py:254: in copyfile
    with open(src, 'rb') as fsrc:
E   FileNotFoundError: [Errno 2] No such file or directory: 'freebayes-snakemake/tests/data/sample1_R1.fastq.gz'
```

I think it would probably be fine to simply skip the copying of "git" files if they are missing, and let the user figure out what is going on. Most likely, they removed those files just moments before, so the fact that they are not copied should not surprise them.

**Comment by rhpvorderman** [comment]
I don't like skipping silently. We should post a warning. Or even better, catch this exception and throw a better one.
"Files checked in to git were not present. Did you check in the removals, or use `git rm`"? Or something along those lines.
What I like about `--git-aware` is that it only copies checked in files, so it reduces the chances of "it worked on my system" errors. So an exception in that spirit would be good.

**Comment by Redmar-van-den-Berg** [comment]
That also sounds good!
