### ISSUE TITLE
pytest-workflow crashes when git submodules are missing

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [LUMC/pytest-workflow#139]
When using the `--git-aware` flag, pytest-workflow crashes with a wall of errors if your project has git submodules, but you haven't cloned the submodules yet. It is hard to tell from the error messages what is going on.

In my case, this error message is one of 13 errors, it appears this error is printed once for every test case that is defined.
```python
___________________________________________________________________________________ ERROR collecting tests/test_functional.yml ____________________________________________________________________________________
../../miniconda3/envs/HAMLET/lib/python3.10/site-packages/pytest_workflow/plugin.py:439: in collect
    workflow = self.queue_workflow()
../../miniconda3/envs/HAMLET/lib/python3.10/site-packages/pytest_workflow/plugin.py:397: in queue_workflow
    duplicate_tree(root_dir, tempdir,
../../miniconda3/envs/HAMLET/lib/python3.10/site-packages/pytest_workflow/util.py:161: in duplicate_tree
    copy(src_path, dest_path)
../../miniconda3/envs/HAMLET/lib/python3.10/shutil.py:434: in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
../../miniconda3/envs/HAMLET/lib/python3.10/shutil.py:254: in copyfile
    with open(src, 'rb') as fsrc:
E   IsADirectoryError: [Errno 21] Is a directory: '/home/user/devel/prod-test/hamlet'
```

Proposed solution: Check to see if all git submodules are present when using `--git--aware`, and immediately abort with one informative error message if they are missing.

**Comment by rhpvorderman** [comment]
Looks like this will be a simple fix. `git submodule status` reports all submodules and adds a `-` in front of the commit if not initialized. The command can even be run as `git submodule status --recursive` so also nested submodules can be found.
The error can then suggest that the user run `git submodule update --init --recursive` which should solve all problems.
