### ISSUE TITLE
Plugin doesn't work nicely with pytest-cov

### ISSUE THREAD

**Issue by sndrtj** [LUMC/pytest-workflow#14]
On a repository with additional regular pytest tests together with the pytest-cov plugin, the coverage no longer makes sense, since pytest-cov also considers the copied sources in `/tmp` to be sources. E.g.

```
----------- coverage: platform linux, python 3.6.7-final-0 -----------
Name                                      Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------
src/create_db.py                             62     12    81%   91-93, 160-174
src/db_to_vcf.py                             41      4    90%   114-118
/tmp/pytest_wfl77b19ib/src/create_db.py      62     62     0%   16-174
/tmp/pytest_wfl77b19ib/src/db_to_vcf.py      41     41     0%   16-118
/tmp/pytest_wfwexbmt2j/src/create_db.py      62     62     0%   16-174
/tmp/pytest_wfwexbmt2j/src/db_to_vcf.py      41     41     0%   16-118
-----------------------------------------------------------------------
TOTAL                                       309    222    28%
```

Running `coverage run --source=src -m py.test -v tests` does work as expected.

**Comment by rhpvorderman** [comment]
This problem is unsolvable due to how this plugin works. Unless we find a better way of running the workflows this will always be an issue. Luckily there is a workaround that mitigates the problem.
The problem is now documented in the known issue documentation, including the workaround you provided here.
