### ISSUE TITLE
Use of Google Cloud Storage outside GCE

### ISSUE THREAD

**Issue by lmtani** [LUMC/pytest-workflow#148]
Hi,

Is there a way to use _Google application default credentials_ or env var _GOOGLE_APPLICATION_CREDENTIALS_ to configure access to Google Cloud Storage private buckets? I saw in the docs that it is possible for S3, but for GCS looks like it will only work in a GCE instance.

![image](https://user-images.githubusercontent.com/12699242/199804299-b7d8caab-cd46-42b6-80ee-7b6cb994b26b.png)

Thanks in advance,

**Comment by rhpvorderman** [comment]
We did a write up on the usage of env vars in the latest documentation: https://pytest-workflow.readthedocs.io/en/latest/#environment-variables

Is that sufficient information to get started?

**Comment by lmtani** [comment]
Hello @rhpvorderman ! I just realize that I've opened this issue thinking in the Miniwdl repository. Sorry!

Thank you for your support, I'll read the doc you linked here, it'll help for sure. 

Closing this issue :)
