### ISSUE TITLE
Workflow testing at scale using SLURM

### ISSUE THREAD

**Issue by wholtz** [LUMC/pytest-workflow#158]
This is a request for input and not a bug report or feature request.

I'm using pytest-workflow to do pipeline testing using tiny datasets and it is working great. But I'd like to add in some at-scale tests that will need to run in an HPC environment where SLURM is the job scheduler. I'm starting to think through how to best use pytest-workflow along with SLURM.

It would be easy to submit one SLURM job per pytest invocation. But if that pytest invocation runs multiple workflows, then allocating the right resources for each workflow could be difficult. Mapping multiple workflows onto a single SLURM job feels like a mismatch of abstractions. 

I could have one SLURM job for a pytest invocation which I limit to running one workflow.  Then I would have to make some higher level script to allow me to submit multiple workflows for testing and to collect up the outputs of several pytest invocations.

The third option is to have pytest-workflow submit a SLURM job for each workflow being tested. This seems the cleanest option, but it requires dealing with the asynchronous nature of SLURM jobs. It may be possible to use something like [Submitit](https://github.com/facebookincubator/submitit) to encapsulate job submission, polling, and retrieval. 

I'm likely going to dig into the third option in a couple of days, but I'm curious if anyone else has suggestions. I'm guessing I'm not the only person who has faced this issue. Thanks!

**Comment by rhpvorderman** [comment]
Hi @wholtz, we designed pytest-workflow with also this use case in my mind.  Some feedback:

- The tests of pytest-workflow execute fairly fast and can run fine on a single thread.
- The workflows take up the bulk (>99% in most cases) of the execution time.

This means that running pytest-workflow on the submit node of a cluster causes no issues, as long as the workflows are properly submitted. So how do we do this?

Our workflows ([BioWDL](https://github.com/biowdl/)) run WDL using cromwell to run the workflows. Cromwell can be configured to submit the workflows to SLURM. So we simply make sure that locally Cromwell uses a configuration that uses docker and on our cluster it uses the cluster configuration. This way we can execute the workflows locally and on the cluster without issues.

May I ask what tools and workflow language you are using?

**Comment by stevekm** [comment]
I would think that the solution for this is definitely going to be in using a workflow framework that has native support for HPC cluster submission. cwltool / Toil, Nextflow, and others, already support submitting to the cluster. You would probably want to leverage that instead of trying to do it from the test runner

**Comment by wholtz** [comment]
Thanks for the replies. For some reason I thought that cromwell only supported the SLURM backend when running in server mode (and not when using the `run` sub-command). I will make use of `cromwell run` with the SLURM backend.
