### ISSUE TITLE
Files are read twice even if no patterns are given

### ISSUE THREAD

**Issue by fabianegli** [LUMC/pytest-workflow#160]
The below code will open files and loop through them regardless of the presence of patterns to match against.

I propose to make the file opening conditional based on the presence of patterns.

https://github.com/LUMC/pytest-workflow/blob/ef7f3121f689f9ff1ba8b477ce5e081a23d24a88/src/pytest_workflow/content_tests.py#L147-L156

e.g:
```python
            if strings_to_check:
                with file_open(mode='rt') as file_handler:  # type: ignore  # mypy goes crazy here otherwise  # noqa: E501
                    self.found_strings = check_content(
                        strings=strings_to_check,
                        text_lines=file_handler)
            if patterns_to_check:
                with file_open(mode='rt') as file_handler:  # type: ignore  # mypy goes crazy here otherwise  # noqa: E501
                    self.found_patterns = check_regex_content(
                        patterns=patterns_to_check,
                        text_lines=file_handler)
```

**Comment by rhpvorderman** [comment]
Good find. I will see if I can fix this before the next release.

**Comment by rhpvorderman** [comment]
I did a double check. While the files are opened, due to the nature of the iterator the file is not read when there are no patterns. 
Even so it is a shame to read the file twice when there are both regexes and strings so that is also fixed now.
