### ISSUE TITLE
File encodings can not be defined when opening files for content tests

### ISSUE THREAD

**Issue by fabianegli** [LUMC/pytest-workflow#161]
It would probably be nice if one could pass file encodings to the tests to make sure the files are read with the right encoding.

The way it is set up now open will infer the encoding with `locale.getpreferredencoding(False)`. However, if a process produces a file in another encoding, tests will inadvertently break.

https://github.com/LUMC/pytest-workflow/blob/ef7f3121f689f9ff1ba8b477ce5e081a23d24a88/src/pytest_workflow/content_tests.py#L148

**Comment by rhpvorderman** [comment]
Another good catch. Currently our use case for pytest-workflow is only on linux where everything is UTF-8 encoded. For frequent platform-hoppers this might be an issue. I will put this on the backlog until somebody reports an actual crash. . Does this cause errors for you at the moment?

**Comment by fabianegli** [comment]
I can imagine pytest-workflow to be useful in a multi-language setting and there someone might have to work with files in various encodings.

Having said that the issue arose in a context where a control character popped up in a log file that was tested with a contains clause. Because the control character ('\x14') can not be validly decoded in utf-8, this lead to the test failure although the failing decoding was on a later line that the contains string.

**Comment by rhpvorderman** [comment]
The latest development version should have the fix. Can you check if the problem still remains?

**Comment by rhpvorderman** [comment]
Fixed in the newest release 2.0.0.
