### ISSUE TITLE
bioconda package is outdated

### ISSUE THREAD

**Issue by stevekm** [LUMC/pytest-workflow#173]
When trying to install `pytest-workflow` with `conda`, I found that there is a package on bioconda;

https://anaconda.org/bioconda/pytest-workflow

However it is very outdated. The one on conda-forge seems to be the one to use;

https://anaconda.org/conda-forge/pytest-workflow

However, in my conda environment YAML, I have other packages that come from bioconda, so it seems like conda is installing `pytest-workflow` from bioconda instead of the version from conda-forge, since both are listed in my channels list for the env.

Can the bioconda package just be removed since its outdated?

**Comment by DavyCats** [comment]
Removing a package from a conda channel is generally discouraged, as it messes with reproducibility/backwards-compatibility.

Generally speaking the solution here would to specify the (minimum) desired version in your yaml. Alternatively, you could set the conda-forge channel as having a higher priority than bioconda and setting the channal_priority to "strict". This is also recommended in the bioconda docs: https://bioconda.github.io/#usage.

**Comment by stevekm** [comment]
sounds good, thanks!
