### ISSUE TITLE
is it possible to run pytest and only run non-pytest-workflow tests

### ISSUE THREAD

**Issue by sstrong99** [LUMC/pytest-workflow#186]
I have a repository with a mix of standard pytest unit tests as well as pytest-workflow tests. Is it possible to select only the non-pytest-workflow ones to run?

**Comment by rhpvorderman** [comment]
Workflows are tagged with their name. If you add `--tag R2D2` none of the workflows should run. (Unless R2D2 is in the name, but this is unlikely). Technically any tag that does not match would work.

**Comment by sstrong99** [comment]
thanks!

**Comment by rhpvorderman** [comment]
Thanks for reporting back.
