### ISSUE TITLE
Feature request: Only run assertions (--skip-command?)

### ISSUE THREAD

**Issue by stianlagstad** [LUMC/pytest-workflow#195]
Thank you again for this valuable tool.

Sometimes I have an expensive command which takes a long time, and in those cases I would like the ability to only run that command once and then iterate on my assertions without having to re-run the command. Could that be made possible with something like a flag `--skip-command`, or with something like `--only-run-assertions`?

**Comment by rhpvorderman** [comment]
This is similar to #174 if I am not mistaken. Yes, this would be very useful to have!

**Comment by stianlagstad** [comment]
Thank you. Closing in favor of https://github.com/LUMC/pytest-workflow/issues/176.
