### ISSUE TITLE
Exceptions raised in one of the workflow threads hangs tool indefinitely

### ISSUE THREAD

**Issue by sndrtj** [LUMC/pytest-workflow#61]
Consider the following yaml file

```yaml
- name: a-test
  command: a command with a dangling double-quote"
```

This causes a `ValueError` in `shex.split`. The error is not propagated to the main thread, which causes the tool to hang indefinitely, until it is killed with SIGTERM or SIGKILL.

**Comment by rhpvorderman** [comment]
:+1: 
This is a nice test case to implement in the test suite.

We will have to look into event handling in python, which is a nice learning opportunity.
