### ISSUE TITLE
Improve cooperation with Travis

### ISSUE THREAD

**Issue by rhpvorderman** [LUMC/pytest-workflow#62]
Travis fails if no output was received for ten minutes.
When running pipelines that depend on containers, these containers need to be pulled, which takes time and will lead to a timeout all the time receiving no output.

A "still running" message that displays when pipelines are running every minute that can be enabled with `--travis` or something could fix this.

**Comment by DavyCats** [comment]
Travis has a built-in mechanic like this already: [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received). An example of this in use can be seen [here](https://travis-ci.org/biowdl/RNA-seq/jobs/496946866).

**Comment by rhpvorderman** [comment]
Oh that solves the problem nicely. Thanks @DavyCats .
