### ISSUE TITLE
Add option to be git aware

### ISSUE THREAD

**Issue by rhpvorderman** [LUMC/pytest-workflow#78]
Pytest-workflow copies the current working directory. This can give problems if the current working directory includes large environment folders.

Also pytest has to be run from the root directory of the workflow.

If pytest-workflow becomes git-aware, it always knows what the root directory is, and will run from there. It can also only copy files that are added to git. This will make copying faster and will make the results more reproducible.

**Comment by OvalAdmin** [comment]
I would like to suggest that instead of being "git aware" it might be better to be "Manifest" aware. The code within setup tools that processes ``manifest.in`` allows for quite fine grained file/folder selection. 

I can't find a good reference for the actual code however there is a related package [manifest-tool](https://pypi.org/project/manifest-tool/). I haven't used it though.

**Comment by rhpvorderman** [comment]
One of the explicit purposes of pytest-workflow is not to have code specific to any type of language or project. Adding manifest aware code would only benefit python projects. Keeping this code as simple as possible has the advantage of avoiding bugs, which in a test framework is paramount. I have seen other test frameworks where testing was hampered by bugs in the framework. Consequently two projects needed to be debugged, the tested project and the test framework project. In these cases the test framework creates a double burden. 

Having said that it is good to limit which files get copied. Maybe with an ignore directory flag type. The thing about git awareness is that it is very simple. `git ls-files --recursive` basically hands the paths needed to be copied on a platter. Also git is a general tool. I believe over 90% of version-controlled projects use it now. It would be perfect to integrate into pytest-workflow.

- Relatively little code needed to make it work.
- Covers a very broad use case.

This will deliver a lot of value and the trade-off with the maintenance effort is worth it in my opinion.

**Comment by OvalAdmin** [comment]
I meant more that the machinery within setup tools that handles manifest files might be useful for this purpose. If you are going the git route [dulwich](https://www.dulwich.io/) might prove useful; I saw in a talk that it is written entirely in Python and does not make command line calls to git and thought to mention it .

**Comment by rhpvorderman** [comment]
Git support is integrated now. Released in 1.6.0
