### ISSUE TITLE
pytest gives an error while the --basedir is not inside the root dir

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [LUMC/pytest-workflow#95]
If the `--basetemp` folder is `/path/to/folder-where-I-run-tests` and the the current directory is `/path/to/folder`, pytest gives an error because it uses string matching to see if the test base folder is inside the current directory. (See https://github.com/LUMC/pytest-workflow/blob/4611224d8278c41490ad45d50823ef8b88d17eb4/src/pytest_workflow/plugin.py#L166)

```
INTERNALERROR> ValueError: '/path/to/folder-where-I-run-tests' is a subdirectory of '/path/to/folder'. Please select a --basetemp that is not in pytest's current working directory.
```

**Comment by rhpvorderman** [comment]
This is not a bug. This is a feature:

Pytest-workflow works by copying the current directory to the test directory, so the tests can be performed without side effects on your current directory. 

If the test directory is a subdirectory of the current directory, the directory will be copied inside itself. This will lead to an infinite recursion of directory copying.

**Comment by rhpvorderman** [comment]
Whoops I see now that I misread your issue! I am sorry, this is indeed a bug. Using pathlib it should be easy to create a fix.
